### ISSUE TITLE
谈谈你对媒体查询的理解

### ISSUE THREAD

**Issue by baixue0111** [baixue0111/webInterView#11]
#### 什么是媒体查询
媒体查询是由一个可选的媒体类型和零个或多个使用媒体功能的限制了样式表范围的表达式组成，例如宽度、高度和颜色。媒体查询，添加自css3，允许内容的呈现针对一个特定的范围的输出设备而进行裁剪，而不必改变内容本身，非常适合web网页对应不同型号的设备而做出对应的响应适配。
#### 如何使用
媒体查询包含⼀个可选的媒体类型和，满⾜CSS3规范的条件下，包含零个或多个表达式，这些表达式描述了媒体特 征，最终会被解析为true或false。如果媒体查询中指定的媒体类型匹配展示⽂档所使⽤的设备类型，并且所有的表达式 的值都是true，那么该媒体查询的结果为true.那么媒体查询内的样式将会⽣效。
```css
<!-- link元素中的CSS媒体查询 --> 
<link rel="stylesheet" media="(max-width: 800px)" href="example.css" /> 
<!-- 样式表中的CSS媒体查询 --> 
<style> 
  @media (max-width: 600px) { .facet_sidebar { display: none; } }
</style>
```
