### ISSUE TITLE
块级元素水平居中的方法（用的比较多的几种方式）

### ISSUE THREAD

**Issue by baixue0111** [baixue0111/webInterView#7]
```css
1. margin: 0 auto 方法
```
```css
.content{
  height: 200px;
  width: 200px;
  margin: 0 atuo;
}
```
```html
<div class="content">我是div</div>
```
```css
2. flex布局
```
```css
.content{
  display: flext;
  justify-content: center;
}
```
```html
<div class="center">
    <div class="flex-div">1</div>
    <div class="flex-div">2</div>
</div>
```
```css
3. 使用transform属性，子属性设置如下：
```
```css
.son{
  position: absolute;
  transform: translate(-50%, 0);
}
```
```css
4. 使用绝对定位方式，以及负值的margin-left，子元素设置如下：
```
```css
.son{
  position: absolute;
  width: 100px;  /* 宽度固定*/
  left: 50%;
  margin-left: -50px; /*负的宽度的一半*/
}
```
```css
5.使用绝对定位方式：left: 0; right: 0; margin: 0 auto; 子元素设置如下：
```
```css
.son{
  position: absolute;
  width: 100px;  /*宽度固定*/
  left: 0;
  right: 0;
  margin: 0 atuo;
}
```
